// ═══ LAYER 1: DATA MODEL (entities, links, cluster config) ═══

export const ENTITY_TYPES = {
  gpu:      { label:'GPU',       color:'rgba(249,115,22,0.82)', stroke:'#fb923c', shape:'rect' },
  cpu:      { label:'CPU',       color:'rgba(59,130,246,0.78)', stroke:'#60a5fa', shape:'rect' },
  nvswitch: { label:'NVSwitch',  color:'rgba(139,92,246,0.88)', stroke:'#a78bfa', shape:'circle' },
  hbm:      { label:'HBM3',      color:'rgba(14,116,144,0.7)',  stroke:'#06b6d4', shape:'rect' },
  nic:      { label:'IB NIC',    color:'rgba(6,78,59,0.78)',    stroke:'#22c55e', shape:'rect' },
  tor:      { label:'ToR',       color:'rgba(6,182,212,0.16)',  stroke:'rgba(6,182,212,0.65)', shape:'circle' },
  spine:    { label:'Spine',     color:'rgba(34,197,94,0.14)',  stroke:'rgba(34,197,94,0.45)', shape:'rect' },
  core:     { label:'Core',      color:'rgba(34,197,94,0.22)',  stroke:'rgba(34,197,94,0.7)',  shape:'rect' },
  rack:     { label:'Rack',      color:'rgba(6,182,212,0.05)',  stroke:'rgba(6,182,212,0.22)', shape:'rect' },
  pod:      { label:'Pod',       color:null, stroke:null, shape:'rect' },
  zone:     { label:'Zone',      color:'rgba(59,130,246,0.022)',stroke:'rgba(59,130,246,0.2)', shape:'rect' },
  node:     { label:'Node',      color:'rgba(10,16,32,0.97)',   stroke:'rgba(34,197,94,0.35)', shape:'rect' },
};

export const LINK_TYPES = {
  nvlink:      { label:'NVLink 4.0',            color:'rgba(249,115,22,0.85)',  dashDraw:false,
                 bw:'900 GB/s 双向 (单 GPU)', total_bw:'900 GB/s × 18 lane',
                 latency:'< 1 μs', encoding:'PAM4 NRZ',
                 use:'节点内 GPU All-to-All 训练数据面；AllReduce/AllGather 不经 CPU' },
  pcie:        { label:'PCIe Gen5 x16',          color:'rgba(139,92,246,0.85)', dashDraw:false,
                 bw:'128 GB/s 双向', latency:'1–4 μs', encoding:'128b/130b',
                 use:'GPU→CPU 控制调度；NIC→GPU GPUDirect DMA；NVSwitch mgmt' },
  upi:         { label:'AMD Infinity Fabric',    color:'rgba(147,197,253,0.85)',dashDraw:false,
                 bw:'~340 GB/s (EPYC)', latency:'~100 ns',
                 use:'双路 CPU 共享内存；NUMA 跨 socket 访问' },
  ib:          { label:'InfiniBand NDR 400Gb/s', color:'rgba(6,182,212,0.85)',  dashDraw:false,
                 bw:'400 Gb/s = 50 GB/s 单 link', node_total:'3.2 Tb/s (8 NIC × 400G)',
                 latency:'< 600 ns MPI level', rdma:'GPUDirect RDMA — 零拷贝', encoding:'64b/66b',
                 use:'跨节点 RDMA 训练通信；8 NIC 绑定每节点 3.2 Tb/s，不经 CPU' },
  ib_node_tor: { label:'IB NDR 400Gb/s (Node→ToR)', color:'rgba(6,182,212,0.85)', dashDraw:false,
                 bw:'400 Gb/s per NIC', node_total:'8× = 3.2 Tb/s per node',
                 latency:'< 600 ns',
                 use:'Node→ToR RDMA；每 GPU 独享一条 400G link (GPUDirect)' },
  ib_tor_spine:{ label:'IB NDR 400Gb/s (ToR→Spine)', color:'rgba(6,182,212,0.85)', dashDraw:false,
                 bw:'4× 400G ECMP 上联', topo:'Fat-Tree leaf-spine，1:1 无阻塞',
                 latency:'100–300 ns switch',
                 use:'Pod 内 non-blocking 汇聚；AllReduce 不出现热点拥塞' },
  eth:         { label:'Ethernet 400GbE',        color:'rgba(34,197,94,0.85)',  dashDraw:true,
                 bw:'400 Gb/s', latency:'~5–10 μs TCP',
                 use:'跨 Pod 路由；连接 Lustre/FSx/S3 存储；管控面 + 外网出口' },
};

// Pod visual themes
export const POD_THEMES = {
  purple: { fill:'rgba(28,24,70,0.55)',  stroke:'rgba(139,92,246,0.25)' },
  green:  { fill:'rgba(18,38,25,0.55)',  stroke:'rgba(34,197,94,0.22)'  },
  blue:   { fill:'rgba(15,30,55,0.55)',  stroke:'rgba(59,130,246,0.25)' },
  orange: { fill:'rgba(40,20,10,0.55)',  stroke:'rgba(249,115,22,0.25)' },
};

// ─── Cluster configuration ────────────────────────────────────────────────────
export const CLUSTER_CONFIG = {
  zone: {
    name:       'Availability Zone',
    totalGPU:   '35,000+',
    network:    '三层 Spine-Leaf + Core',
    storage:    'FSx Lustre / EFS / S3',
    redundancy: '独立供电 + 双路制冷',
  },
  pods: [
    { id:'pod0', name:'Pod A — Training',  racksCount:5, theme:'purple' },
    { id:'pod1', name:'Pod B — Training',  racksCount:5, theme:'purple' },
    { id:'pod2', name:'Pod C — Inference', racksCount:3, theme:'green'  },
  ],
  rack: {
    nodesPerRack: 2,
    heightU:      42,
    cooling:      '液冷 Direct Water Cooling',
    powerKW:      '30~60 kW',
  },
  node: {
    model:         'DGX H100',
    gpuCount:      8,
    cpuCount:      2,
    nvswitchCount: 4,
    nicCount:      8,
    ramTB:         2,
    peakFlops:     '~15.8 PFLOPS FP8',
  },
  gpu: {
    model:        'H100 SXM5',
    vramGB:       80,
    vramType:     'HBM3',
    vramBWTBs:    3.35,
    fp16TFLOPS:   '~1979',
    nvlinkBWGBs:  900,
    pcieLanes:    'Gen5 x16',
    tdpW:         700,
  },
  cpu: {
    model:      'AMD EPYC 9654',
    cores:      96,
    threads:    192,
    ramTB:      2,
    pcieGen:    5,
    role:       '调度·预处理·通信初始化',
  },
  nvswitch: {
    protocol:     'NVLink 4.0',
    bwGBs:        900,
    latency:      '< 1 μs',
    topology:     '全连接 All-to-All',
    countPerNode: 4,
  },
  nic: {
    model:        'Mellanox ConnectX-7',
    protocol:     'InfiniBand NDR / RoCEv2',
    bwGbps:       400,
    latencyNs:    600,
    countPerNode: 8,
    totalTbps:    3.2,
  },
  tor: {
    protocol:     'InfiniBand NDR 400Gb/s',
    ports:        64,
    uplinkCount:  4,
    latency:      '100~300 ns',
  },
  spine: {
    protocol:  'InfiniBand NDR/HDR',
    topology:  'Fat-Tree',
    ratio:     '1:1 全带宽无阻塞',
    model:     'NVIDIA Quantum-2 QM9700',
  },
  core: {
    protocol:  'Ethernet 400GbE',
    role:      '跨Pod路由 + 存储 + 外网',
    latency:   '~5–10 μs TCP',
  },
};

// ─── EDGE METADATA ────────────────────────────────────────────────────────────
export const EDGE_META = {
  nvlink:{
    protocol:'NVLink 4.0',
    bw:'900 GB/s 双向 (单 GPU)',
    total_bw:'900 GB/s × 18 lane',
    latency:'< 1 μs',
    encoding:'PAM4 NRZ',
    use:'节点内 GPU All-to-All 训练数据面；AllReduce/AllGather 不经 CPU',
    color:'rgba(249,115,22,0.85)',
  },
  pcie:{
    protocol:'PCIe Gen5 x16',
    bw:'128 GB/s 双向',
    latency:'1–4 μs',
    encoding:'128b/130b',
    use:'GPU→CPU 控制调度；NIC→GPU GPUDirect DMA 通道；NVSwitch mgmt',
    color:'rgba(139,92,246,0.85)',
  },
  upi:{
    protocol:'AMD Infinity Fabric / Intel UPI',
    bw:'~340 GB/s (EPYC)',
    latency:'~100 ns',
    use:'双路 CPU 共享内存；NUMA 跨 socket 访问',
    color:'rgba(147,197,253,0.85)',
  },
  ib:{
    protocol:'InfiniBand NDR 400Gb/s',
    bw:'400 Gb/s = 50 GB/s 单 link',
    node_total:'3.2 Tb/s (8 NIC × 400G)',
    latency:'< 600 ns MPI level',
    rdma:'GPUDirect RDMA — 零拷贝',
    encoding:'64b/66b',
    use:'跨节点 RDMA 训练通信；8 NIC 绑定实现每节点 3.2 Tb/s，不经 CPU',
    color:'rgba(6,182,212,0.85)',
  },
  eth:{
    protocol:'Ethernet 400GbE',
    bw:'400 Gb/s',
    latency:'~5–10 μs TCP',
    use:'跨 Pod 路由；连接 Lustre/FSx/S3 存储；管控面 + 外网出口',
    color:'rgba(34,197,94,0.85)',
  },
  ib_node_tor:{
    protocol:'InfiniBand NDR 400Gb/s',
    bw:'400 Gb/s per NIC',
    node_total:'8× = 3.2 Tb/s per node',
    latency:'< 600 ns',
    use:'Node → ToR RDMA；每 GPU 独享一条 400G link (GPUDirect)',
    color:'rgba(6,182,212,0.85)',
  },
  ib_tor_spine:{
    protocol:'InfiniBand NDR 400Gb/s',
    bw:'4× 400G ECMP 上联',
    topo:'Fat-Tree leaf-spine，1:1 无阻塞',
    latency:'100–300 ns switch',
    use:'Pod 内 non-blocking 汇聚；保障 AllReduce 不出现热点拥塞',
    color:'rgba(6,182,212,0.85)',
  },
};
